WXDIR = $(WXWIN)

all: common.a

include makefile.include
include ../libs.win

common.a: $(OBJECTS) ../libs.win makefile.include
	ar ruv $@ $(OBJECTS)
	ranlib $@

clean:
	rn $(OBJECTS) core *.rsc *.res

cleanall: clean
	rm $(LIBTARGET)
