#!/usr/bin/env python

env = Environment()

env.ParseConfig('wx-config --cxxflags --libs')

env.Append(CCFLAGS = ['-Wall', '-O2', '-DKICAD'])
env.Append(CPPPATH = ['../include', './bitmaps'])
env.Append(LIBPATH = ['../common'])
env.Append(LIBS    = ['common'])

sources = Split("""
	buildmnu.cpp
	files-io.cpp
	kicad.cpp
	mdiframe.cpp
	preferences.cpp
	prjconfig.cpp
	treeprj.cpp""")

ext_sources = ['../common/infospgm.cpp']

objects = env.Object(sources)
for cur_source in ext_sources:
	objects.append(env.Object(cur_source[10:-4], cur_source))

env.Program('kicad', objects)
