#!/usr/bin/env python

Import('env')

sources = Split("""
	buildmnu.cpp
	files-io.cpp
	kicad.cpp
	mdiframe.cpp
	preferences.cpp
	prjconfig.cpp
	treeprj.cpp""")

ext_sources = ['../common/infospgm.cpp']

obj=env.genobj('program',env)
obj.target='kicad'
obj.ccflags='-DKICAD'
obj.source=sources
obj.extsource=ext_sources
obj.includes='#include #kicad/bitmaps'
obj.libs='common'
obj.libpaths='../common'
obj.execute()