#!/usr/bin/env python

Import('env')

sources = Split("""
	affiche.cpp
	block.cpp
	cfg.cpp
	controle.cpp
	dcode.cpp
	deltrack.cpp
	edit.cpp
	files.cpp
	gerberframe.cpp
	gerbview.cpp
	initpcb.cpp
	lay2plot.cpp
	locate.cpp
	onrightclick.cpp
	options.cpp
	pcbplot.cpp
	readgerb.cpp
	reglage.cpp
	rs274d.cpp
	rs274x.cpp
	set_color.cpp
	struct.cpp
	tool_gerber.cpp
	tracepcb.cpp
	trpiste.cpp
	undelete.cpp""")

ext_sources = Split("""../share/drawframe.cpp
	../share/drawpanel.cpp
	../share/infospgm.cpp
	../share/setpage.cpp
	../share/wxprint.cpp
	../share/zoom.cpp
	../pcbnew/basepcbframe.cpp
	../pcbnew/class_board.cpp
	../pcbnew/class_pcb_text.cpp
	../pcbnew/class_track.cpp
	../pcbnew/classpcb.cpp
	../pcbnew/cursors.cpp""")

obj=env.genobj('program',env)
obj.target='gerbview'
obj.ccflags='-DGERBVIEW -DPCBNEW'
obj.source=sources
obj.extsource=ext_sources
obj.includes='#gerbview #include #common #pcbnew #3d-viewer'
obj.libs='common'
obj.libpaths='../common'
obj.execute()

env.bksys_insttype('PREFIX','bin', 'gerbview')
