#!/usr/bin/env python

Import('env')

sources = Split("""
	autosel.cpp
	cfg.cpp
	class_cvpcb.cpp
	cvframe.cpp
	cvpcb.cpp
	displayframe.cpp
	genequiv.cpp
	genorcad.cpp
	init.cpp
	listboxes.cpp
	listlib.cpp
	loadcmp.cpp
	memoire.cpp
	menucfg.cpp
	options.cpp
	rdorcad.cpp
	rdpcad.cpp
	savecmp.cpp
	setvisu.cpp
	tool_cvpcb.cpp
	viewlnet.cpp
	viewlogi.cpp
	visumod.cpp""")

ext_sources = Split("""
	../common/drawframe.cpp
	../common/drawpanel.cpp
	../common/gr_basic.cpp
	../common/infospgm.cpp
	../common/zoom.cpp
	../pcbnew/basepcbframe.cpp
	../pcbnew/class_board.cpp
	../pcbnew/class_cotation.cpp
	../pcbnew/class_edge_mod.cpp
	../pcbnew/class_equipot.cpp
	../pcbnew/class_mire.cpp
	../pcbnew/class_module.cpp
	../pcbnew/class_pad.cpp
	../pcbnew/class_pcb_text.cpp
	../pcbnew/class_text_mod.cpp
	../pcbnew/class_track.cpp
	../pcbnew/classpcb.cpp
	../pcbnew/ioascii.cpp
	../pcbnew/tracemod.cpp""")

obj=env.genobj('program',env)
obj.target='cvpcb'
obj.ccflags='-DCVPCB'
obj.source=sources
obj.extsource=ext_sources
obj.includes='#cvpcb #include #pcbnew #3d-viewer #cvpcb/bitmaps'
obj.libs='common 3dviewer'
obj.libpaths='../common ../3d-viewer'
obj.execute()

env.bksys_insttype('PREFIX','bin','cvpcb')