#!/usr/bin/env python

Import('env')


#env.Append(CCFLAGS = ['-Wall', '-O2', '-DEESCHEMA'])
#env.Append(CPPPATH = ['./', '../include', './bitmaps'])
#env.Append(LIBPATH = ['../common'])
#env.Append(LIBS    = ['common'])

sources = Split("""
	affiche.cpp
	annotate.cpp
	block.cpp
	block_libedit.cpp
	busentry.cpp
	bus-wire-junction.cpp
	cleanup.cpp
	cmpclass.cpp
	component_class.cpp
	controle.cpp
	dangling_ends.cpp
	database.cpp
	delete.cpp
	delsheet.cpp
	dialog_create_component.cpp
	divers.cpp
	editexte.cpp
	editpart.cpp
	eeclass.cpp
	eeconfig.cpp
	eelayer.cpp
	eelibs1.cpp
	eelibs2.cpp
	eeload.cpp
	eeredraw.cpp
	eeschema.cpp
	eestatus.cpp
	eestring.cpp
	erc.cpp
	files-io.cpp
	find.cpp
	genliste.cpp
	getpart.cpp
	hierarch.cpp
	hotkeys.cpp
	libalias.cpp
	libarch.cpp
	libclass.cpp
	libedit.cpp
	libedit_onleftclick.cpp
	libedit_onrightclick.cpp
	libedit_undo_redo.cpp
	libedpart.cpp
	lib_export.cpp
	libfield.cpp
	libframe.cpp
	locate.cpp
	menubar.cpp
	netform.cpp
	netlist_control.cpp
	netlist.cpp
	onleftclick.cpp
	onrightclick.cpp
	options.cpp
	pinedit.cpp
	plot.cpp
	plothpgl.cpp
	plotps.cpp
	priorque.cpp
	savelib.cpp
	save_schemas.cpp
	schedit.cpp
	schframe.cpp
	selpart.cpp
	sheet.cpp
	sheetlab.cpp
	symbdraw.cpp
	symbedit.cpp
	symbtext.cpp
	tool_lib.cpp
	tool_sch.cpp
	tool_viewlib.cpp
	viewlib_frame.cpp
	viewlibs.cpp""")

ext_sources = Split("""../common/drawframe.cpp
	../common/drawpanel.cpp
	../common/gr_basic.cpp
	../common/infospgm.cpp
	../common/selcolor.cpp
	../common/setpage.cpp
	../common/worksheet.cpp
	../common/wxprint.cpp
	../common/zoom.cpp""")

obj=env.genobj('program',env)
obj.target='eeschema'
obj.ccflags='-DEESCHEMA'
obj.source=sources
obj.extsource=ext_sources
obj.includes='#eeschema #include #eeschema/bitmaps'
obj.libs='common'
obj.libpaths='../common'
obj.execute()

