#!/usr/bin/env python


Import('env')

#env.docfolder('docs/en/', 'en', 'rosegarden/')
#env.docfolder('docs/es/', 'es', 'rosegarden/')
#env.docfolder('docs/de/', 'de', 'rosegarden/')
#env.docfolder('docs/sv/', 'sv', 'rosegarden/')
#env.docfolder('docs/ja/', 'ja', 'rosegarden/')

sources = Split("""
	3d_aux.cpp
	3d_canvas.cpp
	3d_class.cpp
	3d_draw.cpp
	3d_frame.cpp
	3d_read_mesh.cpp
	3d_toolbar.cpp
	trackball.cpp""")

obj=env.genobj('staticlib',env)
obj.target='3dviewer'
obj.source=sources
obj.includes='#include #pcbnew'
obj.execute()
