#!/usr/bin/env python

# All of the subdirectories that contain SConscript files
modules = ['3d-viewer', 'common', 'cvpcb', 'eeschema', 'gerbview', 'kicad', 'pcbnew']

# Load all the SConscript files we use and do a build
for curmod in modules:
   SConscript("%s/SConscript" % curmod)
