#!/usr/bin/env python

Import('env')

sources = Split("""
	base_screen.cpp
	base_struct.cpp
	basicframe.cpp
	bitmaps.cpp
	block_commande.cpp
	common.cpp
	common_plot_functions.cpp
	common_plotHPGL_functions.cpp
	common_plotPS_functions.cpp
	confirm.cpp
	displlst.cpp
	drawtxt.cpp
	eda_dde.cpp
	eda_doc.cpp
	edaappl.cpp
	gestfich.cpp
	get_component_dialog.cpp
	msgpanel.cpp
	projet_config.cpp
	string.cpp
	svg_print.cpp
	toolbars.cpp
	trigo.cpp
	wx/dcsvg.cpp
	wxwineda.cpp""")

obj=env.genobj('staticlib',env)
obj.target='common'
obj.source=sources
obj.includes='#include #common/bitmaps'
obj.execute()

